
before_script:
# Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: return-false.dev.webarq.net
  script:
    - ssh $DEV_SERVER_USER@$DEV_SERVER "cd /var/www/vhosts/dev.webarq.net/return-false.dev.webarq.net/ && git checkout master && git pull origin master && exit"
    - hostname
  only:
    - master

#deploy_production:
#  stage: deploy
#  environment: 
#    name: production
#    url: return-false.dev.webarq.net
#  script:
#    - ssh $PRODUCTION_SERVER_USER@$PRODUCTION_SERVER "cd /var/www/vhosts/dev.webarq.net/return-false.dev.webarq.net/ && git checkout master && git pull origin master && exit"
#    - hostname
#  only:
#    - master
#  when: manual
